### ISSUE TITLE
Hardwired path to jupytergraffiti_data

### ISSUE THREAD

**Issue by psychemedia** [willkessler/jupytergraffiti#21]
I notice that you're using a hardwired path to `jupytergraffiti_data` [here](https://github.com/willkessler/jupytergraffiti/blob/master/jupytergraffiti/js/storage.js#L177).

It would be useful if this path could be set by the *jupytergraffiti* screencast creator (eg they might want to specify a hidden directory or a common directory referenced from several directories containing their own graffitied notebooks), perhaps via a metadata editor / panel reached from / on the graffiti control panel?

A guard to check the existence of, and create otherwise, the directory would probably also make sense?

**Comment by willkessler** [comment]
Thank you for the suggestion! 

What I'm thinking is that when you Activate Graffiti on a notebook, you can enter an (optional) `jupytergraffiti_data` path (relative to the notebook's path) in the confirmation dialog. This will then be stored in the graffiti data block in the notebook-level metadata where you could change it later if you so desired using Jupyter's regular metadata editing facility.

e.g. 
```
 "metadata": {
  "graffiti": {
   "firstAuthorId": "dev",
   "id": "id_hvkb0pc",
   "language": "EN",
   "dataPath": "../other_path",
   "markdownLocked": false
  },
...
```

That is, *unless* you meant a different path for every single graffiti? This wouldn't work because every notebook has its own single manifest file, containing information about all the graffiti in the notebook.

**Comment by psychemedia** [comment]
Hi

Re: diffferent paths, I was meaning the notebook level.

So eg I might have:

```
notebooks/
  .graffitibits/
  week1/
    nbactivity1.ipynb
    nbactivitiy2.ipynb
  week2/
    nbactivity3.ipynb
```
with all the graffiti stuff in the common, hidden directory?

Providing a path via notebook metadata would be handy (notebook arguably needs a more streamlined metadata editing route I think?).

With all the metadata, I'm wondering if/how *jupytergraffiti* will work with things like `jupytext`. Latest [v1.1 `jupytext` release](https://github.com/mwouts/jupytext/releases/tag/1.1.0) supports metadata in the `.md` dual format I think?

**Comment by willkessler** [comment]
```notebooks/
  .graffitibits/
  week1/
    nbactivity1.ipynb
    nbactivitiy2.ipynb
  week2/
    nbactivity3.ipynb
``` 
^^  seems quite doable. Note that you are asking that the directory name for the data is also specified... ie, you want to be able to say something like:

```
"metadata": {
  "graffiti": {
   "firstAuthorId": "dev",
   "id": "id_hvkb0pc",
   "language": "EN",
   "dataPath": "../../.graffitibits",
   "markdownLocked": false
  },
```

... and it would not use `jupytergraffiti_data` as the folder name at all. Right?

Not sure about jupytext, don't have much familiarity with it. If it leaves graffiti metadata at the notebook and the cell level alone, then things should work _except_ for the graffiti added to markdown cells. These are positioned by placing html tags around the text involved. If jupytext should strip these then you'd lose access to the graffiti. (In code cells, the positions of the graffiti are kept via token tracking, not by modifying the code cell contents directly, so that should make it through).

Perhaps you can give jupytext a try and see what transpires?

**Comment by psychemedia** [comment]
I will give it a go when I get a chance - next week probably... gonna be
away from m/cs for a few days...

**Comment by willkessler** [comment]
Sounds good, we should have the customizable data path ready before you get back :-)

**Comment by willkessler** [comment]
Turns out we cannot use a hidden directory because Jupyter will not serve content from hidden directories for security reasons (https://github.com/jupyter/notebook/issues/2382#issue-220046457).  However, you can name the folder with some prefix like `_` to separate it from other types of folders. Stay tuned, this code is almost pushed...

**Comment by willkessler** [comment]
@psychemedia  You can now change the data path.  If you pull the latest version of the repo, you will now find the Graffiti Editor panel has a button for changing the data path and folder. It looks like this:

<img width="206" alt="changeDataDirIcon" src="https://user-images.githubusercontent.com/176268/56936647-69e4ce80-6aad-11e9-9e1a-178c29aee10f.png">

When you click the icon, you will then be prompted to specify a data path as shown here:
<img width="1196" alt="changeDataDirIcon2" src="https://user-images.githubusercontent.com/176268/56936662-7e28cb80-6aad-11e9-898e-f11aeb6af0e9.png">

You can specify a relative path vis-a-vis your notebook's location. Note:

* You cannot use hidden (.-prefixed) directories in the path name as Jupyter will not serve data to Graffiti from those directories for security reasons
* If you change the data path after you've created some Graffiti for the current notebook then you will lose access to those Graffiti. Probably best to change the data path right after you Activate Graffiti.
