### ISSUE TITLE
Can this extension use in jupyterlab？

### ISSUE THREAD

**Issue by hujun123qwe** [willkessler/jupytergraffiti#39]
This extension is awesome using in jupyter notebook.
But i offen use jupyter lab, and want to intall in it.
So, i am not sure jupytergraffiti can do it or not.
If it can, please tell me how to do it?
Thank you very much.

**Comment by willkessler** [comment]
Hello, thank you for checking out Graffiti!

Because JupyterLab is a totally different codebase, Graffiti has not yet been ported to JupyterLab. Therefore it does not yet work in JupyterLab.  However, this is on our roadmap as we also use JupyterLab quite heavily.

Some challenges with working in JupyterLab is that you can have many panels (text editors, shells, csv viewers, etc) that can be interacted with, and that a Graffiti would have to record from. THese may or may not be present during playback so Graffiti would have to restore all panels during playback in order to reproduce the configuration used when the movie recording was made. This is considerably harder than just restoring notebook state alone.  @tugceakin 

Stay tuned!

**Comment by lzfxxx** [comment]
Hi @willkessler, is there any progress on this issue?

**Comment by willkessler** [comment]
@lzfxxx  no progress here. Would you consider contributing to a port to JupyterLab?
