### ISSUE TITLE
Movie not available

### ISSUE THREAD

**Issue by goxdve** [willkessler/jupytergraffiti#45]
Hi, I created a graffiti and recorded, but nothing is created in the `jupytergraffiti_data` folder. When I clicked `Play Movie`, I got 'Movie is not available'.

**Comment by goxdve** [comment]
I tried install option #1 and install option #3 and pip install on Win10 and all methods failed, i.e., I got 'Movie not available'. Then I tried `pip install jupytergraffiti` on Ubuntu wsl and all worked fine.

**Comment by willkessler** [comment]
Win10 has an issue with paths. Do you need to use Graffiti on windows?

**Comment by goxdve** [comment]
Yes, it will be better if it can be used on Win10. I have tried the method in this [issue](https://github.com/willkessler/jupytergraffiti/issues/38), it's ok to create a graffiti and make a recording, but when I tried to play the video, I got this:
![图片](https://user-images.githubusercontent.com/15704591/73053798-b128b000-3ec3-11ea-9b8d-fb55c98c8acc.png)

**Comment by willkessler** [comment]
Windows 10 Home Edition?  To debug this I'll need to spin up a virtual host, probably on Azure. Ideally I'd know more specifics about your Windows version. Also, what installation method did you use? pip, conda, or one of the other methods? thanks

**Comment by goxdve** [comment]
I am using Win10 Home Edition.

Firstly, I create an environment with python3.6 by Miniconda:

```
conda create -n py3 python=3.6
```

Then I install jupyter:

```
pip install jupyter
```

I tried installation option [1](https://github.com/willkessler/jupytergraffiti#installation-option-1-use-pip-or-conda-easiest-option) first:

```
pip install jupytergraffiti
```

In this case, I can create a graffiti, I can add a graffiti button, and I can also use the directives (such as `insert_data_from_file`, etc.), but the problem has always been that I can record, but cannot play, I guess it is data not saved because after recording on a new notebook, the `jupytergraffiti_data` directory was not automatically generated.

Then I tried installation option [4](https://github.com/willkessler/jupytergraffiti#installation-option-4-install-the-graffiti-extension-in-your-own-jupyter-server-most-complex-option), I used the approach in this [issue](https://github.com/willkessler/jupytergraffiti/issues/38):

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension install graffiti_extension --user
jupyter nbextension enable graffiti_extension/main --user
```

Before trying method 4, I actually uninstalled jupytergraffiti via pip. According to the introduction in the README, this will permanently install the extension in the computer's installation of the Jupyter Server, but when I open a notebook, there is no jupytergraffiti button on the page.

**Comment by willkessler** [comment]
Hello @Gxzzz !

I believe I have fixed the issues that was preventing Graffiti from working on Windows systems with the latest pip release (`1.0.1.11`).  Your debugging was helpful to me, as in fact, storing Graffiti on Windows was not working because Graffiti was using certain linux-specific commands to create the manifest and recording files.  Now Graffiti tests for Windows and uses Windows-specific commands like `md`, `rmdir`, `copy`, etc.

Please give Graffiti a try and tell me if things are working ok now or report back on what else might not be working. You'll want to :

`pip uninstall jupytergraffiti`

and then

`pip install jupytergraffiti`

You'll want to remove the graffiti installation you did using installation option 4, above. You can try:

```
jupyter nbextension disable graffiti_extension/main
jupyter nbextension uninstall graffiti_extension --user
```

I was finally able to debug and test all of this on a borrowed Windows 10 laptop, and it all appears to work in Chrome. In Windows Edge, playback works, but not recording of audio, seemingly because `MediaRecorder` is different on Edge (or not enabled). Now I can go back to working on Graffiti on a sane system (*nix) and hope never to debug on Windows again any time soon....

**Comment by goxdve** [comment]
Hi, I just tried jupytergraffiti on Win10. I tried it on Firefox and Edge respectively. Everything works fine on Firefox, but there does exists a situation where the audio cannot be saved on Edge, but I don’t think it’s a problem. For Win10 users , this is good enough, thank you for the fix.

**Comment by willkessler** [comment]
Great. Yes, Edge audio recording is not working. I know it works fine on
Chrome and Firefox, and playback will work on Edge if your viewers only
have that browser, so as long as you have access to Chrome or Firefox for
recording, then you'll be able to create and share Graffiti.
