### ISSUE TITLE
import jupytergraffiti not working despite installation. 

### ISSUE THREAD

**Issue by Unopiece98** [willkessler/jupytergraffiti#57]
I am faced with a strange error. Despite successful installation, via `pip` the import fails.

![image](https://user-images.githubusercontent.com/25799152/80629291-46fa4b00-8a70-11ea-8e50-852eec73500f.png)

![image](https://user-images.githubusercontent.com/25799152/80629196-1fa37e00-8a70-11ea-985b-b0dc387e0015.png)

I even tried on google colab.
![image](https://user-images.githubusercontent.com/25799152/80629461-85900580-8a70-11ea-9ac3-ce7ab4e31080.png)
 
I really can't understand where I am going wrong. Please help me out. Thanks :)

**Comment by willkessler** [comment]
hi,

jupyter graffiti is a plugin, therefore you have to install it on the jupyter server. once installed, you don't need to import it.  (i'm not sure about google collab and jupyter plugins).

if you want to use it via import, you can, but then you must follow installation option #3  in the README.

I haven't tried this on google collab, but if you can find a way to clone the repo into the same directory on collab as your notebook, it should work.

### Installation Option #3: Use the Python Library (Slightly More Involved Option, but does not add code to your system)

Note: Before using this method, you may need to `Trust` your Notebook. This is because Jupyter Graffiti is mostly written in Javascript, and by default, if the Notebook you're adding Graffitis to was not created by you, Jupyter Notebook will not "Trust" it and will not run externally loaded javascript code, for security reasons. To Trust a Notebook, click _File...Trust Notebook_ before running the import command below.

- `git clone` this repo in the same directory where you keep the Notebook(s) you want to add Graffiti to.
- Add and run the following command in a cell in the Notebook you want to start adding Graffiti to:
`import jupytergraffiti`
- If everything works, you will see a button labelled "Activate Graffiti" in your menu bar.

If you don't see this button appearing, use _Kernel... Restart and Clear Output_ first, then try running `import jupytergraffiti` again.

**Comment by willkessler** [comment]
Alternatively, if you want to use it locally, you can use the docker setup, installation option  number 2. Or, you can install it in your local jupyter server, if you have set that up .  Use `pip` or `conda` to install jupytergraffiti, and then restart `jupyter notebook`.

**Comment by willkessler** [comment]
By the way, I tried to use the plugin on Google Colab, but because Colab's design is different than regular jupyter , i dont think the plugin can work in Colab as designed, because Colab is significantly different in its web design than regular Jupyter. If there is evidence people want to use the tool in Colab, I will work on that.

**Comment by willkessler** [comment]
I forgot about another option you can try, if you don't want to install the plugin permanently.

First, clone the repo like this:

```
!git clone https://github.com/willkessler/jupytergraffiti
```

then create a new notebook _inside_ the new `jupytergraffiti` directory containing the contents of the cloned repo.  Now in that new notebook, do

```
import jupytergraffiti
```

and you should see "Activate Graffiti" available to you to turn on Graffiti for this notebook. You can then record Graffiti, etc.

Every time you return to your notebook with Graffiti in it, you will have to do `import jupytergraffiti` again to see the Graffiti, since you are not installing the plugin in the server, only loading it via python temporarily.

**Comment by Unopiece98** [comment]
Hi! Thank you so much for helping me out! Everything you suggested works and I can now see the activate graffiti button. Sorry, this is my first time using a plugin hence the confusion.

However, if I download a notebook that already contains graffiti in it, I can't play it. is it because simply downloading the notebook is not enough?

**Comment by willkessler** [comment]
Right, most of the graffiti data is stored in a directory called `jupytergraffiti_data` that lives alongside the notebook. It contains graffiti recordings data for every notebook found in that same directory. So you need to download that folder as well.

Let me know if you are able to record new graffiti recordings with the system now.

**Comment by Unopiece98** [comment]
Thanks for the tip. Yes, I can record new graffiti now, can't thank you enough 😄
