### ISSUE TITLE
Unable to save Graffiti record

### ISSUE THREAD

**Issue by veilupt** [willkessler/jupytergraffiti#61]
I had run the following command before starting jupyter notebook,
`pip3 install jupytergraffiti`

`jupyter nbextension install graffiti_extension --symlink --user
jupyter nbextension enable graffiti_extension/main --user
jupyter notebook`

### Steps to reproduce this issue:

1. Edit the text that we want to record the video
2. Start the recording and run through the notebook
3. More than one hour the record doesn't save

I was trying to save my notebook run using jupytergraffiti on chrome browser, Refer the screenshot,

![saving_record_graffiti](https://user-images.githubusercontent.com/34787470/89640591-846f3f80-d8cd-11ea-9111-e2b132e58212.png)

## System Environment
OS: Ubuntu 18.04 (Google VM)

**Comment by hndr91** [comment]
Also have same issue with this. I run my jupyter notebook using my own server. I use The Littlest Jupyter Hub

**Comment by willkessler** [comment]
You only need to use either `pip install` or `jupyter nbextension install`, not both.  If the graffiti did not save in a few seconds, then there was an error of some sort. Did you check the browser's console for errors?

**Comment by willkessler** [comment]
BTW, this has been tested extensively using Google VM's, those are built using [this recipe.](https://github.com/willkessler/nvidia-docker-novnc)

**Comment by veilupt** [comment]
@willkessler So this will run using only GPU? I don't have GPU enabled Google VM

**Comment by willkessler** [comment]
No, not at all, that's just what I use to test Graffiti on an ubuntu desktop running on a Google VM.

Can you post a screenshot of the js console here so I can help you sort out your issue?

**Comment by veilupt** [comment]
@willkessler  check this, 
![grafffati-save-error](https://user-images.githubusercontent.com/34787470/90355640-a05fa780-e06a-11ea-951a-0abaa88c0676.png)

**Comment by willkessler** [comment]
Graffiti requires access to the microphone for the audio portion of your movie. Have you granted access to a virtualized microphone? That is why there is a message `Graffiti: Audio recording cannot start access not granted.`  Without the audio, the graffiti movies cannot save.  

Because Graffiti is primarily a "show and tell" tool, like a screencast, it has always been part of the design of the movies that audio would be included so you could explain to the audience the steps you're teaching.  You always have the option of recording graffiti movies locally on your computer where you likely can grant access to the microphone, and then upload those movies to your Google VM for playback.

**Comment by willkessler** [comment]
Note, if you try the demo [here](https://mybinder.org/v2/gh/willkessler/jupytergraffiti/master?filepath=samples%2Fudacity%2Fc%2B%2B_nanodegree%2FFor%20Loops.ipynb), you will find it records audio just fine on Binder. 

So you should be able to access jupyter running on your Google VM just fine in the same way we've [set things up](https://github.com/willkessler/jupytergraffiti/blob/master/jupytergraffiti/postBuild) for Binder hosts.

Maybe you can share a few details on how you set up Jupyter on your GCP hosts?

**Comment by veilupt** [comment]
How to enable audio at playback

**Comment by veilupt** [comment]
I can see the microphone access in the demo link, but unable to detect in the notebook url

**Comment by willkessler** [comment]
On a new host, Chrome will ask you if you want to grant access to the microphone when you try to record a movie for the first time. You should say "yes". Alternatively, you can grant microphone access to your jupyter installation's domain in Chrome preferences.

**Comment by willkessler** [comment]
> I can see the microphone access in the demo link, but unable to detect in the notebook url

Sorry, I'm not sure I understand. What did you mean, precisely? Thank you.

**Comment by veilupt** [comment]
I tried and unable to run because

`API request failed (403): '_xsrf' argument missing from POST`

>  Uncaught (in promise) XhrError: '_xsrf' argument missing from POST
>     at wrap_ajax_error (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:35490:29)
>     at Object.settings.error (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:35546:24)
>     at fire (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:3291:31)
>     at Object.fireWith [as rejectWith] (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:3421:7)
>     at done (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:9535:14)
>     at XMLHttpRequest.<anonymous> (http://host:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:9785:9)
> :8888/api/contents/spark-nlp-workshop/tutorials/Certification_Trainings/Healthcare/Language_Detection_and_Indentification.ipynb:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

```

**Comment by willkessler** [comment]
`API request failed (403): '_xsrf' argument missing from POST` is an error from Jupyter itself, not Graffiti, that has to do with cookies not coming back to Jupyter.  This is an issue that can be solved with a patch to Jupyter.  However, again this should not be necessary...

Have you tried the docker installation locally to see if that works for you? then you could work backwards from that since it's acting like a standalone server...

**Comment by willkessler** [comment]
Assuming you resolved your issue.
