### ISSUE TITLE
Recordings with Matplotlib Widgets

### ISSUE THREAD

**Issue by 4flixt** [willkessler/jupytergraffiti#64]
Dear Will,

thank you for your great tool. We are using it a lot for teaching with Jupyter Notebooks and are very satisfied with the results.

We noticed a minor limitation however: Jupyter Notebooks with Widgets are a great tool for education but unfortunately it seems that Graffiti cannot capture our interactions with the widgets. This would be very beneficial because it allows to explain and interact at the same time. 

I have attached a very simple Jupyter notebook ([recording_with_widget.ipynb.zip](https://github.com/willkessler/jupytergraffiti/files/5830801/recording_with_widget.ipynb.zip)) that show this behavior.

Best,
4flixt

**Comment by willkessler** [comment]
THanks for the heads up. I will take a look over the weekend!

I'd be interested to know where you will be teaching with the tool?

**Comment by willkessler** [comment]
also, is there a specific widget you had in mind?

**Comment by 4flixt** [comment]
The problem arises (from my understanding) whenever we use an interactive matplotlib backend, e.g.:

```
%matplotlib notebook
```

This backend allows to zoom, pan etc. Plots even without further widget functionality (like sliders to change user defined parameters). 
It would be great to record these interactions but Graffiti just shows a blank white space on playback. 

[Here](https://github.com/4flixt/TUB_IoT_MPC20) is an example of a class we taught last semester at Technische Universität Berlin (we are control engineers).

**Comment by willkessler** [comment]
I am looking at your binder examples but there are multiple in that repo, so not sure which one would have an example where you use matplotlib.

However, I have an idea what might be going on. JupyterGraffiti records the contents of the output area of the DOM for any particular cell. It's just recording the html. If the html refers to a canvas or a gif, it won't also record that element, which could be why you're seeing blank. 

however, it looks like matplotlib is generating the images inline to the html, so there's a good chance I could modify graffiti to capture these as well.

Is that the only plugin giving you trouble?

Also, did you know you can annotate code as well as markdown? So you can put tips etc to dress up code in your code cells. You can also attach a movie to a hidden solution, so that when the student clicks "Show solution" you reveal the solution and also explain how it works. Just some ideas. Your notebooks are pretty nice! eg /notebooks/E4/04_Continuous_MPC_OrthogonalCollocation.ipynb

**Comment by willkessler** [comment]
Also, not sure if you saw it, but you may find it useful to use the drawing tools built in to Graffiti while teaching. These will allow you to highlight/draw/add icons. You may want to do this once I get matplotlib working and you can draw on your plots though! :)

**Comment by willkessler** [comment]
Hi @4flixt . I set up your notebooks locally to test things out. I got matplotlib's output to record as part of movies without trouble *if* you don't use "interactive" mode for them during the recording.  In other words, this worked:

```
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import numpy as np

fig = plt.figure()
ax = plt.axes()

x = np.linspace(0, 10, 1000)
ax.plot(x, np.sin(x));
```

or, you can do:

```
%matplotlib notebook
fig = plt.figure()
ax = plt.axes()

x = np.linspace(0, 10, 1000)
ax.plot(x, np.cos(x));
```
and run this cell and switch off "interactive" before you do your graffiti recording.

Students could still run the cell and get interactive after they watch the recording. If you plan to use matplotlib's interactive features during a movie, that would be tougher since I don't think they are rendering these in the dom but probably in a canvas.The browser isn't actually exposing the contents of the canvas to other javascript (like jupytergraffiti's js running while recording) so I'm sort of out of luck to capture those interactions.

Here's a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/176268/105792279-23e7c380-5f3c-11eb-8f71-70be632eabf5.png)

Here's an example of a movie where I marked with the highlighter over a matplot chart

![image](https://user-images.githubusercontent.com/176268/105792538-7d4ff280-5f3c-11eb-9bbe-8539cff6353c.png)

**Comment by willkessler** [comment]
PS I love all your cool annotated notebooks! Great use of the tool!

**Comment by 4flixt** [comment]
Hey Will! Thanks for looking at my problem in great detail and also for the props :) I really appreciate it!

> Also, not sure if you saw it, but you may find it useful to use the drawing tools built in to Graffiti while teaching.

I have been using this feature more and more in the last semester. It is a bit difficult for me to draw with the mouse but I am getting used to it and it creates a lot of added value.

> Hi @4flixt . I set up your notebooks locally to test things out. I got matplotlib's output to record as part of movies without trouble _if_ you don't use "interactive" mode for them during the recording. In other words, this worked:

Non interactive plots work great! I use graffiti all the time to discuss results visualized with matplotlib. My question was really only about the interactive mode of plots. It would have allowed me to illustrate the affect of a parameter (e.g. with a slider) on the output of an algorithm. First I would have shown the effect in a video (with discussion) and then the students could have played with the interactive component themselves. In the end I was hoping to achieve something like [this](https://eater.net/quaternions/video/intro) (but with a lot less work). 

Anyways, I understand your explanation on why this is difficult/impossible to implement. It was really more of a nice to have feature :) 

Best,
4flixt

**Comment by willkessler** [comment]
Cool.  And that demo from eater.net is also pretty slick. I'm curious as to how that was done, so I'll check it out. In general, I love interactive, hands-on learning tools so every new one I find gets me excited.

With respect to "drawing with the mouse" I feel your pain there. One thing you can try is to just use the highlighter tool, which is an alternative to just selecting text.

![image](https://user-images.githubusercontent.com/176268/105869978-a90ac100-5fac-11eb-85c3-d0f3602d3ec1.png)

**Comment by willkessler** [comment]
@4flixt I have updated Graffiti to version 1.0.1.15.

This version now includes a way to clean up unused video takes with a single button click:
![image](https://user-images.githubusercontent.com/176268/107420132-6d541900-6acd-11eb-8533-b35c75c64316.png)

And a new button that will instantly make a Show/Hide button with the contents of the cell you've selected.
![image](https://user-images.githubusercontent.com/176268/107420061-56adc200-6acd-11eb-8cb0-d979af418474.png)

This version also fixes inline terminals, which got broken with a more recent push to Jupyter. In order to use inline terminals you now need at least Jupyter v6.1.6.

Please try these features out and tell me what you think. If you have an existing Graffiti installation you'll have to do `pip upgrade` or `conda upgrade` to get to version 1.0.1.15.

**Comment by 4flixt** [comment]
This is amazing Will! Thank you so much for adding these features. I have just tested them and it works as expected. I have some further suggestions but will add them as separate issues to keep everything more organized.
