### ISSUE TITLE
Edit content of cells that were converted to show/hide solution cells

### ISSUE THREAD

**Issue by 4flixt** [willkessler/jupytergraffiti#72]
When converting a cell to a show/hide solution button jupytergraffiti writes the cells content to an external file that is loaded upon pressing the newly created show/hide button.
As far as I can see, it is not possible to update the content of this solution file directly from the jupyter notebook.
Instead the auto-generated files need to be opened and the content adapted in an external editor. 
Especially, when many proposed solutions are present in the notebook it is very hard to find the corresponding file (since the names are autogenerated and not descriptive). 

Of course it needs to be ensured, that the students working with the jupyter notebook can not easily change the content of the proposed solution (could happen by accident).

**Comment by willkessler** [comment]
@4flixt 

For changing the solution contents, you could Show the solution, edit it, then reclick the conversion button (then delete the cell with first button you made). This will create another include file so you'd have to delete the first one.

If we move the include files next to the graffiti recordings files in graffiti_data, then you could just leave the old files in there and let graffiti keep track of what file to include. It would also make it harder for students to accidentally modify those files since they'll be hard to find.

Does that satisfy your needs?

**Comment by 4flixt** [comment]
I guess that solution would work for me, thank you Will!

**Comment by willkessler** [comment]
This is now done and pushed in v1.0.1.18. Closing this issue and will provide more details on the other issue.
